// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand-directions/Duotone.tsx": () => import("../components/mockups/brand-directions/Duotone.tsx"),
  "./components/mockups/brand-directions/NeonDark.tsx": () => import("../components/mockups/brand-directions/NeonDark.tsx"),
  "./components/mockups/brand-directions/WarmLight.tsx": () => import("../components/mockups/brand-directions/WarmLight.tsx"),
  "./components/mockups/brand-directions/WarmMono.tsx": () => import("../components/mockups/brand-directions/WarmMono.tsx"),
  "./components/mockups/brand-directions/WarmPastel.tsx": () => import("../components/mockups/brand-directions/WarmPastel.tsx"),
  "./components/mockups/brand-directions/WarmRetro.tsx": () => import("../components/mockups/brand-directions/WarmRetro.tsx"),
  "./components/mockups/classlingo-landing/Glass.tsx": () => import("../components/mockups/classlingo-landing/Glass.tsx"),
  "./components/mockups/classlingo-landing/Pastel.tsx": () => import("../components/mockups/classlingo-landing/Pastel.tsx"),
  "./components/mockups/classlingo-landing/Purple.tsx": () => import("../components/mockups/classlingo-landing/Purple.tsx")
};
